version: "3"

tasks:
  default:
    desc: Default task
    cmds:
      - task: test

  test:
    dir: ./sample
    cmds:
      - terraform init
      - terraform apply   -auto-approve
      - terraform output  -raw kubeconfig > k8s_config

  cleanup:
    desc: Clean up after tests
    cmds:
     - echo "Cleaning up..."
